config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" =>  "homes#about", as: "about"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:edit, :index, :show, :update]
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
  validates :title, presence: true
 validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  
   has_one_attached :profile_image
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end
  
  
 
  
    validates :name, presence: true, length: { minimum: 2, maximum: 20}, uniqueness: true 
    validates :introduction, length: { maximum: 50 } 
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
 before_action :authenticate_user!, except: [:top, :about]

 def after_sign_in_path_for(resource)
   user_path(current_user.id)
 end

 def after_sign_out_path_for(resource)
  root_path
 end

 protected

 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :is_matching_login_user, only: [:edit, :update]

  def index
     @books=Book.all
    @book=Book.new
    @user=current_user
  end

  def create
    @book = Book.new(book_params)
   @book.user_id = current_user.id
   if  @book.save
       flash[:notice]= "You have created book successfully."
    redirect_to book_path(@book.id)
   else
       @books=Book.all
        @user=current_user
      render :index
   end
  end

  def show
     @book=Book.new
     @books= Book.find(params[:id])
     @user= @books.user
  end

  def edit
     @book = Book.find(params[:id])
  end

   def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to books_path # 投稿一覧画面へリダイレクト
   end

    def update
      @book = Book.find(params[:id])
     if @book.update(book_params)
        flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book.id)
     else
      render :edit
     end
    end

   private

    def book_params
      params.require(:book).permit(:title, :body, :image)
    end

   def is_matching_login_user
      book = Book.find(params[:id])
      books = book.user
      unless books.id == current_user.id
        redirect_to books_path
      end
   end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :is_matching_login_user, only: [:edit, :update]
  def index
     @users=User.all
    @user=current_user
      @book=Book.new
  end

  def show
      @user=User.find(params[:id])
      @book=Book.new
      @books=@user.books
  end

  def edit
     @user=User.find(params[:id])
  end
  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
      else
        render :edit
      end
  end



  private

    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

     def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
     end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<div class="col-md-3">
<h2>User info</h2>
 <table class="table">
   <tbody>
    <%= image_tag @user.get_profile_image %>
     <tr><th>name</th><th><%= user.name %></th></tr>
    <tr><th>introduction</th><th></th><%= user.introduction %></th></tr>
  </tbody>
</table>

<div class="row">
 <%=link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block " do %>
 <i class="fa-solid fa-user-gear"></i>
 <% end %>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: book do |f| %>
<div class="form-group">
<label for="book_title">Title</label><br>
  <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="form-group">
<label for="book_opinion">Opinion</label><br>
 <%= f.text_area :body, class: "form-control" %>
 </div>
<div class="form-group">
 <%= f.submit 'Create Book', class: "btn btn-success"%>
 </div>
 <% end %>
 </div>
   

app/views/books/edit.html.erb
 
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>
    <% if @book.errors.any? %>
  <h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
    <%= form_with model: @book do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
        <label for="book_opinion">Opinion</label>
         <%= f.text_area :body, class: "form-control book_body" %>
         </div>
         <div class="form-group">
            <p> <%= f.submit 'Update Book', class: "btn btn-success" %></p>
             </div>

               <% end %>
              <%= link_to "Show", book_path(@book.id) %> |
              <%= link_to "Back", books_path %>
     </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
   <% if @book.errors.any? %>
  <h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
    <div class="row">
     <%= render 'books/new', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
     　<h2>Books</h2>
     <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>

    <% @books.each do |book| %>
    <tbody>
    <tr>
    <td><%=link_to user_path(book.user.id) do %>
    <%= image_tag @user.get_profile_image %><% end %>
    </td>
    <td><%= link_to book.title, book_path(book.id) %></td>
    <td><%= book.body %></td>
    </tr>
    </tbody>
     <% end %>


    </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>
<div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'books/new', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">

     　<h2>Book detail</h2>
     <table class="table">
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@user.id) do %>
         <%= image_tag @user.get_profile_image %>
            <%= @books.user.name %>
            <%end%>
          </td>
          <td>
            <%= link_to @books.title, book_path(@books.id) %>
          </td>
          <td>
           <%= @books.body %>
          </td>
          <td>
             <% if @books.user == current_user %>
            <%= link_to "Edit", edit_book_path(@books.id), class: "btn btn-sm btn-success" %>
          <% end %>
          </td>
          <td>
             <% if @books.user == current_user %>
            <%= link_to "Destroy", book_path(@books.id), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
         <% end %>
          </td>
        </tr>


    </tbody>
    </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fa-solid fa-book"></i><strong>Bookers!</strong>
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to<i class="fa-solid fa-book"></i><strong>Bookers!!</strong> </h1>
      <p>In <strong><i class="fa-solid fa-book"></i>Bookers,</strong> </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <% if user_signed_in? %>
   <!--サインインしているとき-->
   <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
     <%= link_to "Log-in", user_path(current_user.id), class: "btn btn-info btn-sm btn-block mb-3 sign_in"%>
    </div>
    <div class="row">
     <%= link_to "Sign-up", user_path(current_user.id), class: "btn btn-success btn-sm btn-block sign_up"%>
    </div>
    <% else %>
    <!--サインインしていないとき-->
    <div class="row">
     <a href="/users/sign_in" class="btn btn-info btn-sm btn-block mb-3 sign_in">Log in</a>
    </div>

    <div class="row">
     <a href="/users/sign_up" class="btn btn-success btn-sm btn-block sign_up">Sign up</a>
    </div>
   </div>
  </div>
 </div>
<</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/a7199d0147.js" crossorigin="anonymous"></script>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">

         <%= link_to "Bookers", root_path, class: "navbar-brand" %>

     <% if user_signed_in? %>
     <ul class="navbar-nav ml-auto">
       <li>
        <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
        <i class="fa-solid fa-house"></i> Home
        <% end %>
       </li>

        <li>
         <%= link_to  users_path, class: "nav-link text-light" do %>
       <i class="fa-solid fa-users"></i> Users
       <% end %>
       </li>

        <li>
         <%= link_to  books_path, class: "nav-link text-light" do %>
      <i class="fa-solid fa-book-open"></i> Books
      <% end %>
       </li>

        <li>
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
        <i class="fa-solid fa-right-from-bracket"></i> Log out
        <% end %>
        </li>
     </ul>
      <% else %>
       <ul class="navbar-nav ml-auto">
       <li>
         <%= link_to  root_path, class: "nav-link text-light" do %>
       <i class="fa-solid fa-house"></i> Home
       <% end %>
        </li>

        <li>
         <%= link_to  about_path, class: "nav-link text-light" do %>
      <i class="fa-solid fa-link"></i> About
      <% end %>
       </li>

        <li>
          <%= link_to  new_user_registration_path, class: "nav-link text-light" do %>
        <i class="fa-solid fa-user-plus"></i> Sign up
        <% end %>
        </li>
        <li>
          <%= link_to  new_user_session_path, class: "nav-link text-light" do %>
        <i class="fa-solid fa-right-to-bracket"></i> Log in
        <% end %>
        </li>
      </ul>
     <% end %>
     </div>
     </nav>
    </header>
    <main> <%= yield %></main>
  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>


  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <% if @user.errors.any? %>
  <h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

    <%= form_with model: @user do |f| %>
    <div class="form-group">
    <label for="user_name">Name</label>
    <%= f.text_field :name, class: "form-control user_name" %>
    </div>
    <div class="form-group">
    <label for="user_image">Image</label>
     <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file" %>
     </div>

    <div class="form-group">
     <label for="user_introduction">Introduction</label>
     <%= f.text_area :introduction, class: "form-control introduction" %>
    </div>

     <div class="form-group">
      <%= f.submit 'Update User', class: "btn btn-secondary"  %>
     </div>
     <% end %>
  </div>
 </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <%= render 'books/new', book: @book, user: @user %>
  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Image</th>
          <th>name</th>
          <th></th>
         </tr>
      </thead>
       <% @users.each do |user| %>
      <tbody>
    
      <tr>
        <td> <%= image_tag user.get_profile_image %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %> </td>
       </tr>
      </tbody>
      <% end %>
    </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<div class="container px-5 px-sm-0">
<div class="row">
 
 <%= render 'books/new', book: @book, user: @user %>
 
<div class="col-md-8 offset-md-1">
 <h2>Books</h2>
 <table class="table table-hover table-inverse">
   <thead>
   <tr>
   <th></th>
   <th>Title</th>
   <th>Opinion</th>
   </tr>
   </thead>
     <% @books.each do |book| %>
     <tbody>
       <tr>
         <td><%= link_to user_path(@user.id) do %>
          <%= image_tag @user.get_profile_image %>
         <% end %>
         </td>
         <td><%= link_to book.title, book_path(book.id) %></td>
         <td><%= book.body %></td>
       </tr>

     </tbody>
     <% end %>
 </table>
  </div>
 </div>
</div>